"""nowe pola

Revision ID: 30e629594b5d
Revises: d3e1616696c8
Create Date: 2025-05-12 09:49:13.013583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e629594b5d'
down_revision = 'd3e1616696c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('o_mnie', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('ostatnio_widziany', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ostatnio_widziany')
        batch_op.drop_column('o_mnie')

    # ### end Alembic commands ###
