"""add column to user

Revision ID: 6fd4320b68f1
Revises: b78de3bcbbae
Create Date: 2025-05-12 09:47:44.933142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd4320b68f1'
down_revision = 'b78de3bcbbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_nazwa'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_column('nazwa')

    # ### end Alembic commands ###
